# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d889450994e52bf3f8f532ee91d0d027c3e0f82866f9378f66b478df789faba9a5c4db75f670aea65339fb8e417921d452e4c98baf1fd5578fc4be822f329e3

test:
  secret_key_base: 84315e65eacd9e11640d15a1c982b16a2594c165457e8f5116475689af99c48b956c4221f18a81dbc905c6a041e9864be70e4e65550c40563cda622d9dc6f836

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
